name: Build Staging (Stable) Build

on:
  push:
    branches: [ upstream ]
  pull_request:
    branches: [ upstream ]

jobs:
  m30s:
    name: Build Galaxy m30s (One UI)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Kolkata"
        timezoneMacos: "Asia/Kolkata"
        timezoneWindows: "Indian Standard Time"
      
    - name: Install Debian/Ubuntu dependencies
      run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install build-essential libelf-dev bzip2 lib32stdc++6 libc6-dev-i386 git -y

    - name: Install Toolchain
      run: |
          set -eo pipefail
          git clone -n https://github.com/CruelKernel/aarch64-cruel-elf.git ${HOME}/toolchain
          cd ${HOME}/toolchain
          git checkout cf641f1153b02a9c6210c3abcf8cc9d4e31a4b3b
          mkdir -p ${HOME}/toolchain_arm32
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz --output-document=${HOME}/toolchain_arm32/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz
          tar -xvf ${HOME}/toolchain_arm32/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz -C ${HOME}/toolchain_arm32

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
          swap-size-gb: 12

    - name: Build Kernel
      run: |
          set -eo pipefail
          echo "  I: Building FreshCore CI $GITHUB_RUN_NUMBER"
          export KBUILD_BUILD_VERSION=$GITHUB_RUN_NUMBER
          ./build.sh m30s ci
          
    - name: Prepare Release
      run: |
          mkdir -p ./release
          cp -f FRSH_CORE_*.zip ./release/
          cp .config ./release/kernel_config_m30s.txt

    - name: Upload image artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy m30s Kernel Image (staging-${{ github.run_number }})
        path: 'tools/package/others/boot.img'
        if-no-files-found: warn

    - name: Upload config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Galaxy m30s Kernel Config (staging-${{ github.run_number }})
        path: 'release/kernel_config_m30s.txt'
        if-no-files-found: error

    - name: Upload release artifacts
      uses: actions/upload-artifact@v2
      with:
        name: m30s_release_staging-${{ github.run_number }})
        path: 'release'
        if-no-files-found: error

    - name: Upload to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        document: FRSH_CORE_m30s*.zip
        message: "OneUI Build"
